##################################################################
#
#	Makefile for xxxx using gcc on Linux. 
#
#
#	Modified	by	Reason
# 	--------	--	------
#	28-Oct-04       CBL     Original
#
# RCS header info.
# ----------------
# $RCSfile$
# $Author$
# $Date$
# $Locker$
# $Name$
# $Revision$
#
# $Log: $
#
#
# Chris Lirakis
# BBN Technologies
# 127 John Clarke Rd.
# Middletown, R.I. 02842
# (401) - 849 - 2543 
######################################################################
# Machine specific stuff
#
#
TARGET = testme
#
# Compile time resolution.
#
INCLUDE =  -I$(DRIVE)/common/utility
LIBS = 

# Rules to make the object files depend on the sources.
SRC     = 
SRCCPP  = main.cpp
SRCS    = $(SRC) $(SRCCPP)

HEADERS = 

# When we build all, what do we build?
all:      $(TARGET)

include $(DRIVE)/common/makefiles/makefile.inc


#dependencies
include make.depend 
# DO NOT DELETE
