/********************************************************************
* My_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error My_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableMy_Dict();
extern void G__cpp_setup_inheritanceMy_Dict();
extern void G__cpp_setup_typetableMy_Dict();
extern void G__cpp_setup_memvarMy_Dict();
extern void G__cpp_setup_globalMy_Dict();
extern void G__cpp_setup_memfuncMy_Dict();
extern void G__cpp_setup_funcMy_Dict();
extern void G__set_cpp_environmentMy_Dict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "Aclock.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__My_DictLN_TClass;
extern G__linked_taginfo G__My_DictLN_TBuffer;
extern G__linked_taginfo G__My_DictLN_TMemberInspector;
extern G__linked_taginfo G__My_DictLN_TObject;
extern G__linked_taginfo G__My_DictLN_TTimer;
extern G__linked_taginfo G__My_DictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__My_DictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__My_DictLN_TQObject;
extern G__linked_taginfo G__My_DictLN_TSysEvtHandler;
extern G__linked_taginfo G__My_DictLN_TPad;
extern G__linked_taginfo G__My_DictLN_MinuteHand;
extern G__linked_taginfo G__My_DictLN_HourHand;
extern G__linked_taginfo G__My_DictLN_SecondHand;
extern G__linked_taginfo G__My_DictLN_Aclock;

/* STUB derived class for protected member access */
