/********************************************************************
* sp_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error sp_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablesp_Dict();
extern void G__cpp_setup_inheritancesp_Dict();
extern void G__cpp_setup_typetablesp_Dict();
extern void G__cpp_setup_memvarsp_Dict();
extern void G__cpp_setup_globalsp_Dict();
extern void G__cpp_setup_memfuncsp_Dict();
extern void G__cpp_setup_funcsp_Dict();
extern void G__set_cpp_environmentsp_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "spiceplot.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__sp_DictLN_TClass;
extern G__linked_taginfo G__sp_DictLN_TBuffer;
extern G__linked_taginfo G__sp_DictLN_TMemberInspector;
extern G__linked_taginfo G__sp_DictLN_TObject;
extern G__linked_taginfo G__sp_DictLN_TList;
extern G__linked_taginfo G__sp_DictLN_TString;
extern G__linked_taginfo G__sp_DictLN_TGObject;
extern G__linked_taginfo G__sp_DictLN_TGWindow;
extern G__linked_taginfo G__sp_DictLN_TPoint;
extern G__linked_taginfo G__sp_DictLN_TQObject;
extern G__linked_taginfo G__sp_DictLN_TGFrame;
extern G__linked_taginfo G__sp_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__sp_DictLN_TGMainFrame;
extern G__linked_taginfo G__sp_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__sp_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__sp_DictLN_TAxis;
extern G__linked_taginfo G__sp_DictLN_TMultiGraph;
extern G__linked_taginfo G__sp_DictLN_TLegend;
extern G__linked_taginfo G__sp_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__sp_DictLN_TGStatusBar;
extern G__linked_taginfo G__sp_DictLN_TGToolBar;
extern G__linked_taginfo G__sp_DictLN_TMarker;
extern G__linked_taginfo G__sp_DictLN_SpicePlot;

/* STUB derived class for protected member access */
