/********************************************************************
* gps_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error gps_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablegps_Dict();
extern void G__cpp_setup_inheritancegps_Dict();
extern void G__cpp_setup_typetablegps_Dict();
extern void G__cpp_setup_memvargps_Dict();
extern void G__cpp_setup_globalgps_Dict();
extern void G__cpp_setup_memfuncgps_Dict();
extern void G__cpp_setup_funcgps_Dict();
extern void G__set_cpp_environmentgps_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "gpsPlot.hh"
#include "CreateTab.hh"
#include "Polar.hh"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__gps_DictLN_TClass;
extern G__linked_taginfo G__gps_DictLN_TBuffer;
extern G__linked_taginfo G__gps_DictLN_TMemberInspector;
extern G__linked_taginfo G__gps_DictLN_TObject;
extern G__linked_taginfo G__gps_DictLN_TList;
extern G__linked_taginfo G__gps_DictLN_TTimer;
extern G__linked_taginfo G__gps_DictLN_TGObject;
extern G__linked_taginfo G__gps_DictLN_TGWindow;
extern G__linked_taginfo G__gps_DictLN_TQObject;
extern G__linked_taginfo G__gps_DictLN_TQObjSender;
extern G__linked_taginfo G__gps_DictLN_TGFrame;
extern G__linked_taginfo G__gps_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__gps_DictLN_TGMainFrame;
extern G__linked_taginfo G__gps_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__gps_DictLN_TGStatusBar;
extern G__linked_taginfo G__gps_DictLN_TGToolBar;
extern G__linked_taginfo G__gps_DictLN_TGTab;
extern G__linked_taginfo G__gps_DictLN_CreateTab;
extern G__linked_taginfo G__gps_DictLN_gpsPlot;
extern G__linked_taginfo G__gps_DictLN_TGWidget;
extern G__linked_taginfo G__gps_DictLN_TEllipse;
extern G__linked_taginfo G__gps_DictLN_TText;
extern G__linked_taginfo G__gps_DictLN_TGraph;
extern G__linked_taginfo G__gps_DictLN_Polar;
extern G__linked_taginfo G__gps_DictLN_TLine;
extern G__linked_taginfo G__gps_DictLN_TPolyMarker;
extern G__linked_taginfo G__gps_DictLN_TMarker;
extern G__linked_taginfo G__gps_DictLN_PolarcLcLdA;

/* STUB derived class for protected member access */
