##################################################################
#
#	Makefile for test of Stations module using gcc on Linux. 
#
#
#	Modified	by	Reason
# 	--------	--	------
#	21-Jan-23       CBL     Original
#       22-Jan-23       CBL     Added in Proj
#
#
######################################################################
# Machine specific stuff
#
#
TARGET = STest
#
# Compile time resolution.
#
EXT_CFLAGS = -g -DMAIN
INCLUDE =  -I$(COMMON)/utility 
LIBS = -lutility -lproj

# Rules to make the object files depend on the sources.
SRC     = 
SRCCPP  = Stations.cpp
SRCS    = $(SRC) $(SRCCPP)

HEADERS = 

# When we build all, what do we build?
all:      $(TARGET)

include $(DRIVE)/common/makefiles/makefile.inc


#dependencies
include make.depend 
# DO NOT DELETE
