/********************************************************************
* RootShowerDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error RootShowerDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableRootShowerDict();
extern void G__cpp_setup_inheritanceRootShowerDict();
extern void G__cpp_setup_typetableRootShowerDict();
extern void G__cpp_setup_memvarRootShowerDict();
extern void G__cpp_setup_globalRootShowerDict();
extern void G__cpp_setup_memfuncRootShowerDict();
extern void G__cpp_setup_funcRootShowerDict();
extern void G__set_cpp_environmentRootShowerDict();
}


#include "TROOT.h"
#include "TMemberInspector.h"
#include "MyParticle.h"
#include "MyDetector.h"
#include "MyEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__RootShowerDictLN_TClass;
extern G__linked_taginfo G__RootShowerDictLN_TBuffer;
extern G__linked_taginfo G__RootShowerDictLN_TMemberInspector;
extern G__linked_taginfo G__RootShowerDictLN_TObject;
extern G__linked_taginfo G__RootShowerDictLN_TObjArray;
extern G__linked_taginfo G__RootShowerDictLN_vectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgR;
extern G__linked_taginfo G__RootShowerDictLN_reverse_iteratorlEvectorlETStreamerInfomUcOallocatorlETStreamerInfomUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootShowerDictLN_TDatime;
extern G__linked_taginfo G__RootShowerDictLN_TAttLine;
extern G__linked_taginfo G__RootShowerDictLN_TClonesArray;
extern G__linked_taginfo G__RootShowerDictLN_TVector3;
extern G__linked_taginfo G__RootShowerDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__RootShowerDictLN_reverse_iteratorlEvectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootShowerDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__RootShowerDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__RootShowerDictLN_TRef;
extern G__linked_taginfo G__RootShowerDictLN_TAtt3D;
extern G__linked_taginfo G__RootShowerDictLN_TPolyLine3D;
extern G__linked_taginfo G__RootShowerDictLN_TParticle;
extern G__linked_taginfo G__RootShowerDictLN_MyParticle;
extern G__linked_taginfo G__RootShowerDictLN_TGeoManager;
extern G__linked_taginfo G__RootShowerDictLN_MyDetector;
extern G__linked_taginfo G__RootShowerDictLN_EventHeader;
extern G__linked_taginfo G__RootShowerDictLN_MyEvent;

/* STUB derived class for protected member access */
